### ISSUE TITLE
[FALSE-POSITIVE] 1923shop.com

### ISSUE THREAD

**Issue by jorge-pedroso** [Phishing-Database/phishing#533]
**Domains or links**
Please list any domains and links listed here which you believe are a false positive.
1923shop.com

**More Information**
How did you discover your web site or domain was listed here?
1. Website was hacked
No. It didn't.
2. Incorrectly marked as Phishing on Phishtank or OpenPhish?
Running Virus Total, I noticed that the domain was incorrectly added to the Phishing list.

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.
https://1923shop.com/

**Additional context**
Updated Imunify to version  7.18.2-2

:exclamation:

We understand being listed on a Phishing Database like this can be frustrating and embarrassing for many web site owners. The first step is to remain calm. The second step is to rest assured one of our maintainers will address your issue as soon as possible. Please make sure you have provided as much information as possible to help speed up the process.

**Send a Pull Request for faster removal**
Users who understand github and creating Pull Requests can assist us with faster removals by sending a PR to **mitchellkrogza/phishing** repository, on the falsepositive.list file
> https://github.com/mitchellkrogza/phishing/blob/main/falsepositive.list
Please include the same above information to help speed up the whitelisting process.

**Comment by jorge-pedroso** [comment]
How long does it take for a domain not to be detected by Virus Total after this is included on the false positive list?

**Comment by spirillen** [comment]
> How long does it take for a domain not to be detected by Virus Total after this is included on the false positive list?

Please see my response here https://github.com/Phishing-Database/Phishing.Database/issues/953#issuecomment-2558054262
